### ISSUE TITLE
Webpack cant resolve module 'babel-runtime'

### ISSUE THREAD

**Issue by MrRoyce** [jeffbski/redux-logic#10]
Hi there, I've just started using this library and its going well except for an issue that I haven't been able to resolve.  I'm not sure what's causing it, but it started when I installed this library and the required RXJs libraray, and updated WebPack (1.13.2) and Babel (core 6.14) to handle the ES2016 features.  

The babel-runtime is in dependencies, babel-plugin-transform-runtime is in devDependencies, I've tried clearing the NPM cache, removing and reinstalling node_modules, changing parameters on the webpack CommonsChunkPlugin, .bablerc, etc for 2 days and the exception is still thrown in the browser.  Even odder, the application seems to be working, but I cant have this browser exception.

Here is the output from webpack --display-error-details

```
> webpack --display-error-details

clean-webpack-plugin: /Applications/MAMP/htdocs/tonight/build has been removed.
Hash: 5d841416e86a960afb3d
Version: webpack 1.13.2
Time: 58269ms
                           Asset       Size  Chunks             Chunk Names
                      robots.txt   26 bytes          [emitted]
  vendor.b47001ac2219ce9e5fe0.js    3.09 MB    0, 2  [emitted]  vendor
manifest.7f098e6c96f193b21664.js  763 bytes       2  [emitted]  manifest
    app.edc2af931ca5a3a1776b.css    16.2 kB    1, 2  [emitted]  app
                     favicon.ico    1.15 kB          [emitted]
                      index.html    2.04 kB          [emitted]
     app.edc2af931ca5a3a1776b.js    2.39 MB    1, 2  [emitted]  app
           styles/icon-style.css    1.14 kB          [emitted]
               fonts/icomoon.svg    8.34 kB          [emitted]
               fonts/icomoon.eot    3.26 kB          [emitted]
              fonts/icomoon.woff    3.18 kB          [emitted]
               fonts/icomoon.ttf     3.1 kB          [emitted]
   [0] multi vendor 496 bytes {0} [built] [1 error]
    + 2483 hidden modules

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'babel-runtime' in /Applications/MAMP/htdocs/tonight
resolve module babel-runtime in /Applications/MAMP/htdocs/tonight
  looking for modules in /Applications/MAMP/htdocs/tonight
    /Applications/MAMP/htdocs/tonight/babel-runtime doesn't exist (module as directory)
    resolve 'file' babel-runtime in /Applications/MAMP/htdocs/tonight
      resolve file
        /Applications/MAMP/htdocs/tonight/babel-runtime doesn't exist
        /Applications/MAMP/htdocs/tonight/babel-runtime.js doesn't exist
        /Applications/MAMP/htdocs/tonight/babel-runtime.jsx doesn't exist
  looking for modules in /Applications/MAMP/htdocs/tonight/node_modules
    resolve 'file' babel-runtime in /Applications/MAMP/htdocs/tonight/node_modules
      resolve file
        /Applications/MAMP/htdocs/tonight/node_modules/babel-runtime is not a file
        /Applications/MAMP/htdocs/tonight/node_modules/babel-runtime.js doesn't exist
        /Applications/MAMP/htdocs/tonight/node_modules/babel-runtime.jsx doesn't exist
    resolve 'file' or 'directory' /Applications/MAMP/htdocs/tonight/node_modules/babel-runtime
      resolve file
        /Applications/MAMP/htdocs/tonight/node_modules/babel-runtime is not a file
        /Applications/MAMP/htdocs/tonight/node_modules/babel-runtime.js doesn't exist
        /Applications/MAMP/htdocs/tonight/node_modules/babel-runtime.jsx doesn't exist
      resolve directory
        directory default file index
          resolve file index in /Applications/MAMP/htdocs/tonight/node_modules/babel-runtime
            /Applications/MAMP/htdocs/tonight/node_modules/babel-runtime/index doesn't exist
            /Applications/MAMP/htdocs/tonight/node_modules/babel-runtime/index.js doesn't exist
            /Applications/MAMP/htdocs/tonight/node_modules/babel-runtime/index.jsx doesn't exist
[/Applications/MAMP/htdocs/tonight/babel-runtime]
[/Applications/MAMP/htdocs/tonight/babel-runtime]
[/Applications/MAMP/htdocs/tonight/babel-runtime.js]
[/Applications/MAMP/htdocs/tonight/babel-runtime.jsx]
[/Applications/MAMP/htdocs/tonight/node_modules/babel-runtime.js]
[/Applications/MAMP/htdocs/tonight/node_modules/babel-runtime.js]
[/Applications/MAMP/htdocs/tonight/node_modules/babel-runtime.jsx]
[/Applications/MAMP/htdocs/tonight/node_modules/babel-runtime.jsx]
[/Applications/MAMP/htdocs/tonight/node_modules/babel-runtime/index]
[/Applications/MAMP/htdocs/tonight/node_modules/babel-runtime/index.js]
[/Applications/MAMP/htdocs/tonight/node_modules/babel-runtime/index.jsx]
```

Here is .babelrc

```
{
  "presets": [
    "es2015",
    "es2016",
    "react"
  ],
  "plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }],
    "syntax-async-functions",
    "transform-class-properties",
    "transform-regenerator",
    "transform-object-rest-spread"
  ]
}
```

Any help is appreciated

**Comment by jeffbski** [comment]
Babel can be a little tricky to get setup properly, but I'll see if I can help you figure it out.

Typically in most of my projects these days I require as a dependency babel-core and babel-loader (for webpack), but yes you should be able to use babel-runtime along with the transform-runtime instead. 

Could you point me to a repo or gist with your package.json and webpack config so I can see if I can help you figure out the problem?

You also might just try to see if using babel-core and babel-loader first without the transform-runtime to see if things work that way, then we can for sure know that it is something to do with the babel-runtime and transform setup.

**Comment by MrRoyce** [comment]
Hi Jeff, thanks for taking a look at this.  Here are the gists:

package.json https://gist.github.com/MrRoyce/4f017e273f77181daaea63776b382c1f

webpack.config.js https://gist.github.com/MrRoyce/280063164a5f744cb0ec3ecc36be84a7

babel.prod.js https://gist.github.com/MrRoyce/3ba2f36e50cab5fc8c3c17122f8c0e6d

webpack error log https://gist.github.com/MrRoyce/a834a0da679c9073b0d6a84cb468c566

The other piece of information that may be relevant is that I did NOT use the create-react-app for this application.  I had started it a few months ago before that starter kit was available.  I was using @bebraw survive.js as a base and that was going fine.   

I posted about this problem on the survive.js site and he recommended that I use your babel.prod.js config instead of the very simple one that I was using.  I tried that, but the problem still occurs.

Thanks again for your help with this.

Royce

**Comment by jeffbski** [comment]
Royce,

I assume that your project lives in '/Applications/MAMP/htdocs/tonight' from where webpack is looking for its files.

One of the lines in the webpack error log says that 

/Applications/MAMP/htdocs/tonight/node_modules/babel-runtime doesn't exist

Can you check that this directory does exist and in it is the code for babel-runtime?

Does `npm ls` return any warnings?

For some reason it just looks like the module isn't where it is expected to be.

**Comment by MrRoyce** [comment]
Yes, the directory does exist, here is a screen shot of it.  I don't see any index.js file, but I'm not sure if that file is supposed to be there, or even how I can check to see if the index.js file is on GitHub/NPM??  I do see an index.js file in the regenerator sub-directory, should babel be using that file??

![screen shot 2016-09-26 at 9 13 04 pm](https://cloud.githubusercontent.com/assets/252359/18856987/096bb946-842e-11e6-91a0-4b3167329f98.png)


The only error I see on npm ls, is an error I've been getting for weeks for something with a bad peer dependency:

npm ERR! peer dep missing: react-dom@^0.14.0, required by react-overlays@0.5.4

**Comment by jeffbski** [comment]
Well from looking at https://github.com/babel/babel/tree/master/packages/babel-runtime it looks like in its package.json it doesn't define a main so it would default to index.js if it existed. Though maybe babel-runtime never actually is required directly, maybe it always transforms into requiring a relative path like babel-runtime/core-js/foo in which case there wouldn't need to be an index.js

Though it looks like in webpack that it is actually looking for the default import for babel-runtime which doesn't exist. So the next question is why?

Are you requiring babel-runtime directly anywhere in your code?

It is my understanding that you would not do that. It is something only injected by babel itself and it should be using a module relative require not requiring babel-runtime but babel-runtime/...

**Comment by MrRoyce** [comment]
Thanks for the quick response!

No, I never heard of babel-runtime, and never used it in my code.  I just did a quick search in my 'src' directory and it doesn't show anywhere.  

If I do a search in the entire app including node_modules, the only places it shows up is in package.json?

I've thought about writing a bug on the babel page, but I'm not sure if it is a real bug or something with my configuration.  Plus it seems they have hundreds of open issues, and not enough time or resources to sort through them all.

**Comment by nicholaswyoung** [comment]
@MrRoyce You enabled `regenerator` to transpile generator functions (I assume?). To my knowledge, enabling `regenerator` requires `babel-runtime` (in versions after v6).

You have two options. Disable `regenerator` (if you aren't using ES2015 Generators), or configure Babel's [Transform Runtime Plugin](https://babeljs.io/docs/plugins/transform-runtime/).

**Comment by jeffbski** [comment]
I don't believe there is anything we need to do with redux-logic for this issue (it seems to be a webpack/babel configuration issue). I'll close it for now.

**Comment by hkjpotato** [comment]
For anyone still having the same issue, I think u might encounter this problem when u want to bundle babel-runtime into either common chunk or webpack DLL. It is not going to work because babel-runtime does not have a 'main' in their package json, it is exposed as several utilities function, not as a module. Thus it can not be resolved.
