### ISSUE TITLE
RX jsfiddle's - Rx.umd.js not found

### ISSUE THREAD

**Issue by michael-wolfenden** [jeffbski/redux-logic#12]
Looks like the RX umd package referenced by the RX jsfiddle samples no longer exists thus breaking the samples

https://npmcdn.com/@reactivex/rxjs@5.0.0-rc.1/dist/global/Rx.umd.js
> Not found: file "/dist/global/Rx.umd.js" in package @reactivex/rxjs@5.0.0-rc.1

Appears that `Rx.umd.js` has been renamed to `Rx.js` so the new url is:

https://npmcdn.com/@reactivex/rxjs@5.0.0-rc.1/dist/global/Rx.js

**Comment by jeffbski** [comment]
Thanks! I have updated the fiddles using Rx. I went ahead and used the new domain name too unpkg.com, eventually I'll have to update the other resources to use unpkg.com too.
