### ISSUE TITLE
Question: A way to wait for actions within process? 

### ISSUE THREAD

**Issue by henninghall** [jeffbski/redux-logic#123]
Great library, appreciate it! 

I have previously used redux saga and their effect creator "take" which waits for an action before continuing. Is there a way to achieve this in redux-logic? 

It could hypothetically look like this: 

```
async process({ getState, action }, dispatch, done) {
        dispatch({ type: 'action1'})
        const success = take({ type: 'action1_success'})
}
```

**Comment by jeffbski** [comment]
Thanks for the kind words.

Yes, with the latest version (v2), you now have access to the full action stream as `action$`. 

We can listen to action$ and wait for one or more actions before continuing.

I need to add some examples but for your example it would look something like this.

PS. you will need access to rxjs 5 or 6, I'll use v6 for the example below

```shell
npm i rxjs . # installs rxjs@6
``` 

```js
import {filter, take, tap} from 'rxjs/operators';

... createLogic ...

async process({ getState, action, action$ }, dispatch, done) {
  dispatch({ type: 'action1'})
  action$.pipe(
    filter(a => a.type === 'action1_success'),
    take(1) // we only wait for one and then finish
    tap(a => { // we can use the payload from the action if we want
       dispatch({ type: 'another_action' })
    })
  ).subscribe({ complete: () => done() })
}
```

Technically you don't even need the `async` unless you are using await in your code, but no problem leaving it in.

Alternatively if we need to wait for multiple actions it could look something like this

```js
import {zip} from 'rxjs';
import {filter, take, tap} from 'rxjs/operators';

... createLogic ...

async process({ getState, action, action$ }, dispatch, done) {
  dispatch({ type: 'action1'})
  const action1Success$ = action$.pipe(filter(a => a.type === 'action1_success'));
  const action2Success$ = action$.pipe(filter(a => a.type === 'action2_success'));
  zip(action1Success$, action2Success$).pipe( // we want to wait for one of each
    take(1) // we only wait for one pair and then finish, emits as an array
    tap(arr => { // we can use the payload from the action if we want
        const [a1, a2] = arr; // action1Success, action2Success  
        // we can use payloads from a1 and a2 if desired     
        dispatch({ type: 'another_action' })
    })
  ).subscribe({ complete: () => done() })
}

```

There's many variations on how this can be done, but hopefully this helps.

I'll create more examples eventually.

**Comment by henninghall** [comment]
Nice, awesome answer! 👍 
That's great, I will definitely try it out! May not be as clean syntax as the "take" in redux-saga but since the rest of the redux-logic syntax is much more in my taste, it's probably something we will go with.

**Comment by jeffbski** [comment]
Thanks! yeah, I am thinking about how I might make this type of thing more native so one wouldn't have to jump out to observables, but it's not too terrible with the raw code.
