### ISSUE TITLE
Composing processors

### ISSUE THREAD

**Issue by skbolton** [jeffbski/redux-logic#130]
I am having a hard time coordinating processors in my app. I'll try and come up with a contrived example to explain my problem. Lets say that I already have a processor `A` that handles liking a post, and a processor `B` for commenting on someones post. Later a requirement comes to be able to like and comment on someones post. 

My thinking was that I can in a new processor `C` that could dispatch the action that `A` would pick up on and then listen for its fulfilled action and then dispatch the action that `B` would pick up. It would be a relief if I could also handle if the `C` processor could handle multiple like and comment actions.

My first iteration had me listening to all event types and then filtering the `action$` but I felt like that was not the right direction. Another way that I tried didn't seem to handle when you tried to dispatch liking and commenting again.

**Comment by skbolton** [comment]
I should also mention that my processors are doing this with rxjs and part of my confusion is the observable part

**Comment by jeffbski** [comment]
@skbolton thanks for reaching out. There are lots of ways to approach this and each will have its own trade offs. 

Regardless of how you approach it, somewhere in your code you will be determining what gets done for a particular set of actions. We can move that around but it will still exist somewhere. So whether you are using separate actions and logic for each or whether you have one that listens to all, it will then be deciding what to do. 

Often I find that it is better to do my composition in the functions I call inside of the logic. So I would tend to have unique actions for each thing but then I reuse the functions that do the work. I would break up those functions with smaller functions that are easily composed together. 

I hope that helps. If there is a specific thing you are having trouble implementing, post back and we can continue the discussion.
