### ISSUE TITLE
How init redux-logic when app starts to initialize. Without using type

### ISSUE THREAD

**Issue by noashka** [jeffbski/redux-logic#137]
Hello guys. I can't find answer for a simple question. Maybe you can help me. I use redux-logic in a project. In the project I need to get some default data, for example - currentUser. I dont't want do it in the componentDidMount and dispatch action. How I can init redux-logic when my app starts to initialize ?

**Comment by costolo** [comment]
You could write an action that redux-logic intercepts, and dispatch it when your store is initialized.

e.g.:

// store initialization code
store.dispatch(appInit());
export default store;

**Comment by noashka** [comment]
Thank you for response! It's good idea. I'll try it.

**Comment by costolo** [comment]
No worries!
