### ISSUE TITLE
done cb in finally does not trigger dispatch

### ISSUE THREAD

**Issue by AnirudhaGohokar** [jeffbski/redux-logic#152]
Hi,

I have a process block which has a `try/catch/finally` construct as follows:

```
const getUserLoginLogic = createLogic({
  type: sessionTypes.KEYCLOAK_INIT,
  latest: true, 
  process({ getState, action }, dispatch, done) {
    try {
      keycloak
        .init()
        .then(
          authenticated => {
            dispatch(sessionActions.initializeKeycloakSuccess(keycloak));
          },
          exception => {
            dispatch(sessionActions.initializeKeycloakFailed(exception));
          }
        )
    } catch (exception) {
      dispatch(sessionActions.initializeKeycloakFailed(exception));
    }
    finally {
      //calling done here doesn't dispatch above actions
      done();
    }
  }
});

```
As you can see, am making the `done` cb in finally block. This is not triggering the above dispatches.

If I instead make the call just after dispatch, its working.
```
dispatch(...
done();
```

**Comment by thorn0** [comment]
try-catch-finally doesn't work like this with promises. Your `dispatch` calls happen asynchronously in promise callback when the `process` function has already finished its execution. So your `done` is called before `dispatch`. You can understand it better if you add some console.log here and there to see in what order what happens.

**Comment by AnirudhaGohokar** [comment]
Yup My bad. I think I need to revisit basics. 🗡
