### ISSUE TITLE
Custom actions equality function

### ISSUE THREAD

**Issue by iyn** [jeffbski/redux-logic#16]
Let's say a have a logic for a generic data fetching which allows for fetching from multiple endpoints. Fetching happens after a particular action is dispatched (like `FETCH_DATA`), but action has additional metadata, for example:
```
type: FETCH_DATA,
meta: {
  endpoint: '...',
  resourceID: '...',
}
```

I want to implement remote autocomplete (fetch more specified data as user types), so I thought of using `latest`, `debounce` etc. options with the logic. The problem is when I want to dispatch multiple `FETCH_DATA` for multiple resources (say `users` and `orders`) - logic only looks at the action type when debouncing etc. I think it may be useful to allow for (optional) custom function that would check for action equality. What do you think, @jeffbski?

**Comment by jeffbski** [comment]
Hmm. Is there a reason that you wouldn't want to use different action types for each type of fetching? That seems to be the most common way to handle things. 

I guess the other question is would both of these things be occurring at the same time such that they will conflict with each? Will you actually be searching both at the same time? 

I'll ponder the idea some more.

**Comment by iyn** [comment]
I used to have separate logic for each data fetching types but right now I'm trying to build a generic mechanism (based on `redux-logic`) for doing that, I already have a simple MVP, currently it's tied to my API structure but I'll think about open sourcing it in the future.

You pointed the obvious (in hindsight) thing - the searches won't occur at the same time! I can envision the case when it can happen, but this is just hypothetical case (like when autocomplete is dependent on 2 different data sources). Therefore I'm closing the issue. When/if something changes, I'll post here.

Thank you for your time!

**Comment by jeffbski** [comment]
You are welcome. I appreciate taking the time to discuss these things.
