### ISSUE TITLE
example of post using ajax

### ISSUE THREAD

**Issue by cmrts** [jeffbski/redux-logic#173]
Hello, I have been using this library for some time now using axios.

I am considering using ajax as I had some issues with the set-up for axios post. 

Can you please point me to an example of the ajax post for a simple post action, where I then get the response back which contains confirmation of action and other metadata from the server. 

Also, in case of failure, I would like to dispatch another action.

I have looked at the examples and could not find one close to what I need. I have only seen ajax.getJson examples.

Thanks in advance.

**Comment by jeffbski-rga** [comment]
Sure. I can whip one up. I'll get back to you soon.

**Comment by jeffbski** [comment]
Here is one where I use the latest RxJS v6 with ajax post. I just post hard coded values but you could easily change the body to be whatever. 

https://codesandbox.io/s/async-rxjs6-ajax-post-bq2us?file=/src/index.js

Let me know if you have any questions.

**Comment by cmrts** [comment]
Thank you very much. That is exactly the example I was after.

Much appreciated.

**Comment by jeffbski** [comment]
You are quite welcome. I am glad I was able to help.
