### ISSUE TITLE
how to perform a race condition

### ISSUE THREAD

**Issue by kopax** [jeffbski/redux-logic#22]
```jsx
  const winner = yield race({
    auth: call(getAuthorize, { username, password, isRegistering: false }),
    logout: take(LOGOUT),
  });

  // If `authorize` was the winner...
  if (winner.auth) {
    // ...we send Redux appropiate actions
    yield put(changeForm({ username: '', password: '' })); // Clear form
    forwardTo(pages.pageDashboard.path); // Go to dashboard page
    // If `logout` won...
  } else if (winner.logout) {
    // ...we send Redux appropiate action
    yield call(logout); // Call `logout` effect
    forwardTo(pages.pageLogin.path); // Go to root page
  }
```

Is it possible to produce a race like this saga ?

**Comment by jeffbski** [comment]
If I understand the code you have presented it appears that the desired goal is to make an auth request and if in the meantime they click logout, then you would instead log them out. And possibly the reverse as well, if they are logging out and an auth request comes in, perform that instead.

That is easily accomplished in redux-logic with a cancelType declaration. I split the work done from an auth success into its own logic.

```js
const authLogic = createLogic({
  type: AUTHORIZE, // action that triggers the authorization
  cancelType: LOGOUT, // action that would cancel a pending authorization
  process({ getState, action }) {
    const { username, password, isRegistering } = action.payload;
    return getAuthorize({ username, password, isRegistering })
      .then(() => ({ type: AUTH_SUCCESS }));
  }
});

const authSuccessLogic = createLogic({
  type: AUTH_SUCCESS,
  process({ getState, action }) {
    forwardTo(pages.pageDashboard.path);
    return changeForm({ username: '', password: '' }); // action to clear logic form data
  }
});

const logoutLogic = createLogic({
  type: LOGOUT, // action that triggers the logout
  cancelType: AUTHORIZE, // action that would cancel a pending logout
  process({ getState, action }) {
    return logout()
      .then(() => forwardTo(pages.pageLogin.path))
  }
});
```

So in either case if you are processing an auth and you get a logout request or vice versa the previous work will be cancelled. 

----

Now as to the question about whether you can do races with redux-logic, yes you just do this in your code using Observables, Promise.race, or other helper lib.

Let's say you want to hit multiple services and just use the first that comes back.

Assuming our api.callService1() and api.callService2() return a promise resolving to the data.

Here is an example using Observable.race()

```js
const getFoo = createLogic({
  type: 'FOO',
  process({ getState, action }) {
    return Observable.race(
      Observable.fromPromise(api.callService1()),
      Observable.fromPromise(api.callService2())
    ).then(results => fooSuccess(results));
  }
});
```

or if you want to stick with promises, you could use Bluebird's Promise.race()

```js
const getFoo = createLogic({
  type: 'FOO',
  process({ getState, action }) {
    return Promise.race([
      api.callService1(),
      api.callService2()
    ]).then(results => fooSuccess(results));
  }
});
```

**Comment by kopax** [comment]
> So in either case if you are processing an auth and you get a logout request or vice versa the previous work will be cancelled.

This is fine, but what about if I also need to cancel the logics in `LOCATION_CHANGE` ?

**Comment by jeffbski** [comment]
@kopax can you give me an example use case so I can understand? Also is LOCATION_CHANGE the action which requests a route change or is it the action indicating that a route change has already occured.

**Comment by kopax** [comment]
@jeffbski , 

Let say a logout is in proress while an authorize request as been dispatch end is sending for updating the jwt.
The logout perform first, we absolutely need to cancel the jwt update.

So the updating jwt logic will be canceled on LOCATION_CHANGE, but we also need to cancel it on SUBMIT_LOGOUT_REQUEST.

**Comment by jeffbski** [comment]
You can also pass an array or regex to cancelType so if you want to cancel logic on both of those

```js
const fooLogic = createLogic({
  type: FOO,
  cancelType: [ LOCATION_CHANGE, SUBMIT_LOGOUT_REQUEST ], // cancels on any of these
  ...
});
```

**Comment by kopax** [comment]
Thanks a lot, that make sens now. This should be added to the doc I think.

**Comment by jeffbski** [comment]
I've started a guide that walks people through more of those details, so I'll make sure to highlight that. Thanks.
