### ISSUE TITLE
Check for and add error.message when auto-dispatching failTypes

### ISSUE THREAD

**Issue by jktravis** [jeffbski/redux-logic#27]
Hi. I'm using the auto-dispatch method now in most all of my "logics". However, I have found that unless a Promise is explicitly rejected, the error message doesn't seem to be added to the resulting `failType`'s payload, and no message is written to the console. 

Would it be possible to check and add `error.message` to the payload if it exists? 

Here is a sample that you can setup to try this out. 

```javascript
const testingLogic = createLogic({
  type: 'TESTING',
  latest: true,
  processOptions: {
    successType: 'TESTING_SUCCESS',
    failType: 'TESTING_FAILURE'
  },

  process({action}) {
    return new Promise((resolve, reject) => {
      if (action.payload === 'fail') {
        reject('Failed with reject');
      } else if (action.payload === 'pass') {
        resolve('passed');
      } else {
        const foo = action.get('foo'); // There is no `get` method on action
      }
    });
  }
});
```

Then, in Redux tools, dispatch the following:

```javascript
{
  type: 'TESTING',
  payload: 'fail'
}
```

This will result in a nice action with an error message:

```javascript
{
  type: 'TESTING_FAILURE',
  payload: 'Failed with reject',
  error: true
}
```

However, sending `foo` through as the `payload` like so:

```javascript
{
  type: 'TESTING',
  payload: 'foo'
}
```

Results in a dispatched action with no error message, and of course, no console message either.

```javascript
{
  type: 'TESTING_FAILURE',
  payload: {},
  error: true
}
```

**Comment by jeffbski** [comment]
@jktravis Thanks for raising this. Let me take a close look at what you have identified here. I'm certainly in support of improving the error handling capabilities how ever we can.

**Comment by jeffbski** [comment]
@jktravis I haven't forgotten, just need to think through all the various cases here. I'll respond with more soon.

**Comment by jktravis** [comment]
Sure thing. Take your time.

**Comment by jeffbski** [comment]
I'm looking through this in conjunction with #36 so hopefully I'll get it resolved to your liking. Maybe tomorrow if things go well.

**Comment by jeffbski** [comment]
@jktravis I have merged #36 and in the process refactored the code that deals with the dispatch and return value handling especially in regards to errors. I documented the details in the api docs and added a bunch of tests to make sure I verified each of these cases. 

So long story short, this should work now. If you reject with a string, it should show up as the payload for a failType action type. If yo provide instead an action creator fn for failType then it is provided as the only parameter and then you can handle how you want. 

I tested as many error situations as I could think of including throwing errors. 

Hopefully this should resolve everything for you. If not, just let me know.

**Comment by jktravis** [comment]
Thanks. @jeffbski. I think this will work nicely. Much appreciated!

**Comment by jeffbski** [comment]
Fantastic!

**Comment by jktravis** [comment]
This seems so simple now. Don't know why I didn't think of it it earlier. I'll leave the below in case someone comes by later wanting to see specifically how I addressed this. 

**createErrorHandler.js**

```javascript
function handleError (type, error) {
  console.error(error);
  let payload;
  if (typeof error === 'string') {
    payload = error;
  } else if (error.message) {
    payload = error.message;
  }
  return {type, payload, error: true };
}

export function createErrorHandler(type) {
  return function (error) {
    return handleError(type, error);
  }
}
```

**testLogic.js**

```javascript
// Demonstrates the usage of the former. 
import { createLogic } from 'redux-logic';

import { createErrorHandler } from './createErrorHandler';

const testErrorHandler = createErrorHandler('TESTING_FAILURE');

const testingLogic = createLogic({
  type: 'TESTING',
  latest: true,
  processOptions: {
    successType: 'TESTING_SUCCESS',
    failType: testErrorHandler
  },

  process({action}) {
    return new Promise((resolve, reject) => {
      if (action.payload === 'fail') {
        reject('Failed with reject');
      } else if (action.payload === 'pass') {
        resolve('passed');
      } else {
        const foo = action.get('foo'); // There is no `get` method on action
        foo.toString();
      }
    });
  }
});
```

**Comment by jeffbski** [comment]
We'll add some good ideas like that to the usage guide that I have planned. A cookbook of how to solve common problems. Thanks!
