### ISSUE TITLE
Request - example using web sockets.

### ISSUE THREAD

**Issue by Sotorin** [jeffbski/redux-logic#28]
Perhaps community would benefit from a small example using web sockets in addition to classic ajax requests. I'm clear on how to send messages to the server but not sure how to deal with messages arriving from the server.

**Comment by gihrig** [comment]
I would be interested in such an example as well. 

I have a project that will require this feature, but I won't be working on that for a month or more, so an example would be good place to start.

**Comment by jeffbski** [comment]
Great idea! I will add one.

**Comment by jeffbski** [comment]
Here is an example using redux-logic with websockets https://jsfiddle.net/jeffbski/baqz3rkj/

It basically sends whatever msg you type to the websocket service at echo.websocket.org and then it adds all the responses (which are the same since it is an echo service) to a list and displays them.

**Comment by therealgilles** [comment]
Hi, I am trying to use/modify this code. I want the client to send back a message when it receives a specific message from the server. I am dispatching the response message sending with store.dispatch in msgRec before returning { type: MSG_REC }. But this seems to lead to msgRec being called again with the same message.

Note that I have also merged SEND_MSG_CHANGED and MSG_SEND together, as my message is not send through a form field.

I am thinking that sending the message triggers MSG_LISTEN and somehow calls msgRec again with the same message. Any advice would be appreciated. Thank you.

**Comment by therealgilles** [comment]
Nevermind, I forgot that getState.wsConnected would not work for me, as I am using a selector, so selector.wsConnected(getState()) fixed things up.

**Comment by jeffbski** [comment]
Excellent! Thanks for updating us @therealgilles

**Comment by jeffbski** [comment]
FYI. I have a more recent example using redux-logic@2 and rxjs@6 

https://codesandbox.io/s/m38l7n745y

**Comment by therealgilles** [comment]
@jeffbski: The example is missing error handling through failType. How should I add it back in?

**Comment by therealgilles** [comment]
From what I can see, the example is not tracking the connection status, it's tracking the state of the connect/disconnect button, which is not the same thing.

I am not sure how to implement error handling. If you could point me to an example or documentation, it would be great.

The older version of the example also had a retry mechanism in case of disconnection, which is missing here. In my app, it means I have to manually hit refresh to reconnect the socket, whereas it was automatic before.

I am trying to see if I can adapt the older version to rxjs@6 but I am not yet well versed on it. Any help/advice will be appreciated.
