### ISSUE TITLE
Idea: allow return of promise or observable to signal completion, enabling free dispatch

### ISSUE THREAD

**Issue by jeffbski** [jeffbski/redux-logic#3]
One of the potentially confusing parts of the current API is for multi-dispatching. 

For the logic to know when it is complete we need to somehow communicate that in our code. 

If you dispatch an observable or use processOptions.dispatchReturn (where you can return an object, error, promise, or observable) then we can know from these when the code is done, so that works great for those use cases.

However I don't want to force everyone to use promises or observables so we allow the developer to signal completion by expecting a single call of the dispatch function. Since I think the most common use case is to do a single dispatch, that makes a good fallback plan. However when the user wants to make multiple dispatches then it gets tricky. They need to either dispatch an observable or use the second parameter in the dispatch function `dispatch(action, { allowMore: true })` to indicate they aren't done and then the final dispatch without `allowMore` set to end.

So I think this could be confusing to people once they want to do multiple dispatches and they are not using observables. They would likely not remember they have to do something special to enable that.

After reviewing how `redial` works, it allows free dispatching but uses a returned promise to indicate completion. Thus it doesn't do anything with the value coming back, but uses that to signal it is done. It is expected that the user will dispatch any values or errors but returning the promise to signal it is done.

This got me thinking that we could do the same thing. 

Here's how it could work:

First if processOptions.dispatchReturn is true, then nothing would change, it would still dispatch the object, error, or results from promise/observable returned.

So assuming you need to do multiple dispatches and are not using an observable to do that, then a different process option could enable that.

``` js
processOptions: {
  // enables free dispatching if the code returns a promise or observable
  completeReturn: true // complete when the returned promise/observable is done
}
```

Thus if the code returns a promise or observable that would be used to signal completion. This would enable the dispatch to be free to be used for multi-dispatching. If the user doesn't return a promise or observable, then we'd expect a single dispatch as the way it works today (or they can still override with the allowMore flag).

By allowing free dispatching in the promise code, it makes it easy to dispatch things in different steps of the promise chain as you receive the results. 

It is also nice that async functions (async/await) return a promise. So I can imagine many people using that when they need to perform many operations in one set of code. Simply by returning the result of the async function (a promise) they will be able to use free (multiple) dispatching as well.

So I'm currently thinking that this might even be a good default. If they enable `dispatchReturn` that takes priority and goes the extra step of dispatching for them, but otherwise by default completeReturn could be defaulted to on.

This feature only becomes active if they return a promise or observable, so if they don't then it works as it does today (expecting single dispatch). But once they start returning a promise or observable (or returning from an async function) then we start using that to determine completion.

What do you think? Any thoughts or other ideas?

**Comment by tehnomaag** [comment]
Yep, I can see a use for that, so one doesn't have to manually pass the `allowMore` every time and make sure to close with empty dispatch manually.

It's easy to add a `.finally(() => dispatch());` when using Bluebird promises to make sure logic ends properly, but with more standard Promises it can be a pain to make sure you call `dispatch()` in your `.catch` handlers etc.

So this change proposal would simplify that indeed.

**Comment by jeffbski** [comment]
With v0.10 I introduced an easier way to deal with multiple dispatch. 

It simply involves providing an extra callback `done` parameter to enable free multiple dispatch. 

By including the third `done` parameter, it sets the new processOption.dispatchMultiple default to true, enabling this mode.

You can also set the processOption.dispatchMultiple to true for the same effect.

When you are done dispatching you simply call `done()`
