### ISSUE TITLE
Question:  Process similar events in order

### ISSUE THREAD

**Issue by java2kus** [jeffbski/redux-logic#30]
I have a use case where actions are to be processed in order in the following way:

Event order: 
---a1---a2---a3--b1---b2--b3--a4---b4

Processing Order
---a1---a2---a3----------------a4------
-----------------b1---b2--b3---------b4

All actions need to be processed in order and a2 should be dispatched to Redux logic only after a1 has been processed by reducer and the state of 'a' is updated in store.   a1 can also have some side effects that could in turn generate a11, a12 actions. which again have to be processed in order. After all the events with respect to a1 have been processed by reducers and state updated in store, I want a2 to be dispatched to redux-logic.     Similarly I want to process 'b' events without blocking for a.

Is the above possible?

**Comment by jeffbski** [comment]
The way redux is defined currently there isn't a mechanism to know when a particular action has made it all the way through all the middleware and reducer especially when there is asynchronous processing.

I think it would be nice if it had that capability, but I think in some ways the (event sourcing/flux) philosophy is that we shouldn't try to have strict controls around the processing of events, they are more fire and forget. 

One could probably add middleware at the bottom of the stack that would track when an action clears the bottom, but even that would have some edge cases to consider.


However what you have listed above looks a lot like a couple of observables (even using the observable type marble notation).

So if you perform your async scheduling with observables then you can wait for a previous operation to complete before continuing with the next one (using an observable operator like mergeMap).

Thus each operation would be coordinated through observables and you can get the exact ordering you are looking for. The code for each piece could still dispatch actions but those would be synchronous just for used updating the reducer. All the asynchronous scheduling is handled by the observable chain.

redux-logic makes it easy to work with observables, you can simply create and return the observable.

The hard part is in building up the observable chain to perform all this. It's not that complicated but it takes some knowledge of observables to get it right.

```js
import { Observable } from 'rxjs';
const { from } = Observable; // converts promise to Observable

const fooLogic = createLogic({
  type: A1,
  process({ getState, action }, dispatch, done) {
    const id = action.payload;
    // create our observable with from performA1Work
    // which could return a promise or observable
    from(performA1Work(id)) 
      .do(a1Result => dispatch(a1Success(a1Result)))
      .mergeMap(a1Result => from(performA2Work(a1Result)))
      .do(a2Result => dispatch(a2Success(a2Result)))
      .mergeMap(a2Result => from(performA3Work(a2Result)))
      .do(a3Result => dispatch(a3Success(a3Result)))
      .do(a3Result => done());
  }
});    
```

You could also do similar things using promises or async/await.

```js
const fooLogic = createLogic({
  type: A1,
  async process({ getState, action }, dispatch, done) {
    const id = action.payload;
    const a1Result = await performA1Work(id);
    dispatch(a1Success(a1Result));
    const a2Result = await performA2Work(a1Result);
    dispatch(a2Success(a1Result));
    const a3Result = await performA3Work(a2Result);
    dispatch(a2Success(a3Result));
    done();
  }
});    
```

PS. I'll be discussing more about using Observables in my upcoming webinars and live training, so stay tuned. I'll be announcing more info about them soon.

**Comment by java2kus** [comment]
Thanks very much for the elaborate answer.   The reason why we have such a use case is because each of those events depend on the state inside the redux-logic validate/transform function to push the next action.  Also, a1, a2 etc. actions have async calls which have to be processed in order as these events are coming from websockets and only delta changes are being published.   We implemented it by subscribing to the store updates and then pushing the related events through the chain once the reducers have written the updates.

Regarding the webinars/live training, can you please let me know which website has it?

**Comment by jeffbski** [comment]
You are welcome. Glad to help however I can. 

I'll be updating http://codewinds.com/rxjs with more information soon. 

You can also subscribe to my newsletter for both tips and announcements from most any page.
