### ISSUE TITLE
Server side rendering implementation?

### ISSUE THREAD

**Issue by MikeJSX** [jeffbski/redux-logic#37]
I'm getting `cannot assign logicMiddleware instance to multiple stores, create separate instance for each` when try to load it on server few times.

**Comment by jeffbski** [comment]
@MikeJSX Thanks for reaching out. What this error is attempting to communicate is that you should create a fresh instance of logicMiddleware for each store.

So what you could do is in the function where you create your fresh store for each request on the server, also call createLogicMiddleware there too so you have one to one.

```js
function handleServerRequest(req, res) {
  // fresh logicMiddleware to go along with fresh store for each request
  const logicMiddleware = createLogicMiddleware(logic, injectedDeps);
  const enhancer = applyMiddleware(logicMiddleware);
  const store = createStore(reducer, enhancer);
  store.logicMiddleware = logicMiddleware; // for convenience

  // TODO your code

  // Note that if you want to us redux-logic to fetch things you can use 
  // whenComplete to know when the async processing is done
  store.logicMiddleware.whenComplete(() => {
    // all the async redux-logic processing is done so we can now render
    // using the current populated state `store.getState()`
    res.end(...); // send rendered response
  });
}
```

The reason for this restriction is that the logicMiddleware retains a reference to the store internally so you want separate instances corresponding to each store. So this is specifically to protect you when using it in a server situation.

**Comment by MikeJSX** [comment]
Thank you a lot. It solved my problem. Great library!!!

**Comment by jeffbski** [comment]
You are welcome! I'm glad you like it. Have a great day.

**Comment by IzaGz** [comment]
Hello! @MikeJSX , @jeffbski  . Sorry if wrongly created issue `https://github.com/jeffbski/redux-logic/issues/61` , but maybe it is worthy. Maybe someone can provide example starter boilerplate with this great library implemented with server side rendering (ssr) ?

**Comment by yyynnn** [comment]
No problem solved for me. I still get initial state data in the component while SSR. I'm doing this in a async renderer:

```javascript
    const root = (
      <ServerRoot
        location={req.url}
        sheet={sheet.instance}
        store={store}
        context={context}
      />
    )
    store.logicMiddleware.whenComplete(() => {
      const jsx = extractor.collectChunks(root)
      const html = renderToString(jsx)
      const styleTags = sheet.getStyleTags()
      const scriptTags = extractor.getScriptTags()
      const linkTags = extractor.getLinkTags()
      const storeState = store.getState()
      const preloadedState = encodeURIComponent(JSON.stringify(storeState))

      res.status(200).send(
        renderFullPage({
          html,
          styleTags,
          scriptTags,
          linkTags,
          preloadedState,
          meta
        })
      )
    })
```

Like whenComplete ignore logic completion
