### ISSUE TITLE
Cancellation using axios

### ISSUE THREAD

**Issue by michael-wolfenden** [jeffbski/redux-logic#47]
The section on cancellation states

> Many libraries like axios and fetch don't support aborting/cancelling of an in-flight request

However this is no-longer the case with axios which now supports cancellation tokens to cancel requests (see https://github.com/mzabriskie/axios#cancellation)

I am currently using the `cancelType` in my logic to prevent the results the being dispatched, but as you state in the documentation, this does not actually cancel the inflight request.

Is there a hook or anyway to pass a cancellation token to redux-logic so that when the `cancelType` is dispatched, `cancel()` is called on the cancellation token.

**Comment by jeffbski** [comment]
@michael-wolfenden Thanks for the issue. 

Yes you are correct that axios now supports cancellation so yes you can use redux-logic to trigger an xhr cancel.

I had created a jsfiddle that shows how you might accomplish that. I planned on adding this to the documentation as well, but figured I need decent explanations about this which I haven't written yet.

See if this helps to get you going. https://jsfiddle.net/jeffbski/w95q5udg/

**Comment by michael-wolfenden** [comment]
Thanks for the swift reply and awesome library

**Comment by jeffbski** [comment]
Thanks so much for the kind words. I appreciate it.
