### ISSUE TITLE
Errors being swallowed in Reducer

### ISSUE THREAD

**Issue by ksloan** [jeffbski/redux-logic#50]
Hey Jeff,

I'm seeing a similar issue to #46 again except this time it's when the error gets thrown in the reducer itself. 

Here's a fiddle [redacted]
This is a copy of the working demo from #46 except this time the error is being thrown within the reducer itself (on line 68) instead of in render()

**Comment by ksloan** [comment]
Ignore this for now. The fiddle was running version v11.8... and I can't seem to repro with v12.0 in fiddle, but still seeing some weird issues in my app. Will reopen if it has something to do with redux-logic.

**Comment by ksloan** [comment]
@jeffbski I figured out how to repro this. It seems like if you have a logic listening for the same action type as the one throwing the error in the reducer then the error gets swallowed as in #46.

This shows a working version: https://jsfiddle.net/e3cL20zk/2/
This one is hiding the error: https://jsfiddle.net/4cnup8vL/10/

The only difference is line 31, where I'm adding the second logic.
Both fiddles are using redux-logic v0.12.1.

**Comment by jeffbski** [comment]
Thanks for reporting this. I'll take a look and see what I can figure out.

**Comment by ksloan** [comment]
We're you able to confirm this bug? I'm seeing it again today in a different scenario.

**Comment by ksloan** [comment]
Did you ever get a chance to take a look at this?

**Comment by jeffbski** [comment]
@ksloan Thanks for creating the fiddles. I can see what you are running into. I'm not sure what is at play here, but I will look deeper and get to the bottom of it. It feels like this is something to do with the async nature of this, especially when there are multiple logic. I will keep looking into it.

**Comment by jeffbski** [comment]
I believe I found the problem and am working on the solution. I am in the process of confirming tests around it. I should have a fix early next week.

**Comment by ksloan** [comment]
Any updates Jeff?

**Comment by guilhermebruzzi** [comment]
It is happening with me too (redux-logic: 0.12.1), after a long debug session I found an error on a reducer that I had a logic on the same action, and it was swallowed

**Comment by jeffbski** [comment]
arghhh. Sorry @guilhermebruzzi and @ksloan  I was gone last week and am getting back up to speed. I have some time tomorrow when I can focus on it and finish it up. I just want to make sure the fix doesn't cause any other issues so I'm double checking the tests.

**Comment by guilhermebruzzi** [comment]
@jeffbski No problem, thanks for all the hard work that you are doing for this great project! 👍

**Comment by jeffbski** [comment]
thanks @guilhermebruzzi and @ksloan I appreciate the support. I'll keep on it.

**Comment by guilhermebruzzi** [comment]
@ksloan For a workaround adding 'redux-logger' at the end of the middlewares also show the error

**Comment by jeffbski** [comment]
@guilhermebruzzi that's a good idea for a work around.

I did finally get the new version verified and pushed. redux-logic@0.12.2 should now log errors in the reducer or render fn to the console.

**Comment by KevinAst** [comment]
Thanks much @jeffbski.  I upgraded to 0.12.2 and verified it is no longer hiding errors.  Much appreciated!

**Comment by jeffbski** [comment]
Thanks for verifying Kevin!
