### ISSUE TITLE
Question: Can you set warnTimeout globally?

### ISSUE THREAD

**Issue by ksloan** [jeffbski/redux-logic#51]
I'd like to set the warnTimeout default much lower for all my logic, is that possible?

**Comment by jeffbski** [comment]
I guess I should make it possible to change the default. 

In the meantime if you wanted to have a way to set the default you could use a custom createLogic function that wraps the original like this to only set warnTimeout to your new default unless it was specified to a specific value.

```js
import {createLogic} from 'redux-logic';
function myCreateLogic(opt) {
  if (typeof opt.warnTimeout === 'undefined') {
    opt.warnTimeout = 20000; // default to 20s
  }
  return createLogic(opt);
}
```

**Comment by jeffbski** [comment]
deployed in v0.13.0
