### ISSUE TITLE
Redux-logic prevents code errors from being thrown in console

### ISSUE THREAD

**Issue by orosro** [jeffbski/redux-logic#64]
Hello, 

`Version: 0.12.1`
I integrated redux-logic in an application that is in development stage. It happens quite often to have code or logic errors, or any kind of errors. Doesn't matter. Problem is that it's very hard to debug because the errors don't appear in the console anymore after applying logicMiddleware to redux.

```javascript
const logicMiddleware = createLogicMiddleware(arrLogic);
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(Reducers, composeEnhancers(
  applyMiddleware(thunk, logicMiddleware),
));
```

```javascript
const appIsLoaded = createLogic({
  type: APP_LOADING_SUCCESS,
  process({ getState, action }, dispatch, done) {
    console.log('[LOGIC-APP]:: APPLICATION LOADING SUCCESS');
    dispatch(checkLoginToken()); // -- Test if the user is logged in
    done();
  },
  warnTimeout: 0,
});
```

The above is an example logic (minus the export and imports).

From what I managed to understand, after an action is dispatched, redux-logic runs it's watcher thing, but somewhere in the middle of the process, react mounts the component that has an error.

This doesn't happen to all errors :) Am I missing something when creating the logic?

Thank you in advance

**Comment by jeffbski** [comment]
Thanks @orosro for mentioning this. Yes, you are correct, it appears that in certain circumstances the errors can be accidentally masked. A few others had mentioned this in #50 

I believe I have a fix, and am just working through the tests to confirm that it is working properly. I should have this available early next week.

**Comment by orosro** [comment]
Thank you @jeffbski , great work by the way. It solves a lot of issues.

**Comment by orosro** [comment]
@jeffbski Hello Jeff, hope you are well. Any news regarding the bug?  I saw the changes in the PR, When do you think you will do the merge?
We found a workaround in order to see the bug, you can activate the logger in redux, this will output the error in the console. Hope this helps.

`
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import { createLogger } from 'redux-logger';

import { createLogicMiddleware } from 'redux-logic';

import arrLogic from './logic'; // redux-logic files
import Reducers from './reducers'; // react reducers


const logicMiddleware = createLogicMiddleware(arrLogic);

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

const logger = createLogger({
  collapsed: (getState, action, logEntry) => !logEntry.error,
});
const store = createStore(Reducers, composeEnhancers(
  // applyMiddleware(thunk, logger),
  applyMiddleware(thunk, logicMiddleware, logger),
));

if (module.hot) {
  // Enable Webpack hot module replacement for reducers
  module.hot.accept('./reducers', () => {
    /* eslint-disable global-require */
    const nextRootReducer = require('./reducers').default;
    store.replaceReducer(nextRootReducer);
    /* eslint-enable global-require */
  });
}

export default store;
`

**Comment by jeffbski** [comment]
@orosro thanks for the work around. That is a good idea. 

I just pushed a new version redux-logic@0.12.2 which should log the errors now in the console whenever they occur in the reducer or render fns. So hopefully with the new version the work around wouldn't be needed.

**Comment by KevinAst** [comment]
Thanks much @jeffbski.  I upgraded to 0.12.2 and verified it is no longer hiding errors.  Much appreciated!

**Comment by jeffbski** [comment]
Thanks for verifying Kevin!
