### ISSUE TITLE
Unexpected debounce behaviour

### ISSUE THREAD

**Issue by DJTB** [jeffbski/redux-logic#65]
In the [single file example](https://github.com/jeffbski/redux-logic/tree/0198e4ac3d54931e1123b9dc6d8583d0904395d2/examples/single-file)  you mention
> the logic debounce of 500 (ms) has been specified along with latest, so if actions are coming in they will be suppressed until there is 500ms of inactivity when they will allowed to go through. With latest being set true, the take latest feature is enabled so that if multiple requests are made, only the data corresponding to the latest request will be used.

Though I noticed in [logic wrapper](https://github.com/jeffbski/redux-logic/blob/1dd65bf7f517aa52e805ac8e7165fc9117f56444/src/logicWrapper.js):
```
@param {number} logicOptions.debounce milliseconds to perform
  | debouncing, cannot be used with latest, default 0 (disabled)
```
#### A few questions.
1. Can it in fact be used with latest?
2. It appears to be a trailing debounce, not immediate/leading is that correct?
3. Is the debounce only for the listed type/types in the logic that it's listed in, or for *all* activity??

#### An issue:
It appears to debounce on logic init, not after one of the listed types has last occurred.
I have a logic along the lines of: `type: 'LOAD_X_REQUEST'`

When my main page mounts it dispatches the action. With debounce set to 5s, if the app is loaded on that page, the logic won't occur - I assume because 5s hasn't passed since the logic was initialised - though I would expect it to trigger the first action, and *then* debounce further ones into a single action once the debounce time has passed.

Is this intended or am I missing something here?

**Comment by DJTB** [comment]
As a note, I'm using a fork of your react-boilerplate-logic (that has the asyncInjectors logic) integrated with react-router-4.

Logics are working in general, this is the only strange thing that I've come across. Before making a reduced test case, I wanted check my assumptions first.

**Comment by jeffbski** [comment]
1. Yes it can be used with latest. debounce, throttle, and latest can all be used together if necessary.
2. I'm not sure what you mean by trailing vs immediate/leading, the debounce occurs early, right after the filter by types. 
3. It is a debounce for just the types listed for the logic. It won't be for all unless you had used type: '*' or  a regex like /.*/, it will include all the types listed. That filter is being applied first before the debounce. 

Debounce is typically used with things like change events, so we can determine when a user has paused in their typing. So while they are typing nothing happens, but as soon as their is a pause then the the logic runs. With debounce, the last action will fire once the time has passed unless another one comes before that. There is not an initial run.

Throttle is setup after the debounce preventing things from running too often. If something comes in too soon then it is dropped. So if you don't want to run your logic more than once every 5s then you could use this.

latest would drop previous if additional ones come in while they are running.

If you wanted some other type of filtering then you might need to do something custom in your logic based off of timestamp in redux. You'd store a date in ms and check that enough time had passed, set timer, or whatever you need to do. 

If you don't need to load more often then 5s then throttle should do the trick for you. The first call will fire, then additional requests will be dropped until after 5s has passed.

**Comment by DJTB** [comment]
Thanks for the detailed response. I'll likely have to roll my own.

I'm basically after the throttle functionality - but holding onto the latest event during the blackout period, and then firing it after the blackout (instead of simply dropping *all* blackout events).

I'm not using rxjs ajax, otherwise that + `latest` would achieve what I want I suppose :smile:

**Comment by fgiarritiello** [comment]
@DJTB Could you please provide the link to the react-boilerplate-logic + router 4?

I would really appreciate that.

Thanks

**Comment by DJTB** [comment]
@fgiarritiello Hey, I mainly integrated parts of https://github.com/react-boilerplate/react-boilerplate/pull/1746 with https://github.com/jeffbski/react-boilerplate-logic

There isn't a clean example to show you since I made the adjustments to a large in-progress app, sorry!
You'll have to diff those repos and trace the changes.

**Comment by fgiarritiello** [comment]
@DJTB Thanks. That's exactly what I'm currently doing. I'm doing a diff of those projects and trying to update to router 4 on a big existing project. All of this to then get the Hot loading working.

**Comment by fgiarritiello** [comment]
@DJTB Sorry to bother you again, but could you share how you managed to implement the logicInjectors.js? I'm having hard time on that one

Thanks

**Comment by DJTB** [comment]
@fgiarritiello 
https://gist.github.com/DJTB/24abf7ec4426fe16e64dfddbb7d51c15
I jumped in when the RR4 changeover was half done, so this may not reflect how the full PR was completed. Though it's working fine for me.
