### ISSUE TITLE
Errors happening inside reducers were catched by the LogicMiddleware and were not shown

### ISSUE THREAD

**Issue by farukg** [jeffbski/redux-logic#70]
Hello,

i like redux-logic a lot so far, I appreciate your work :)

I found an issue which bothered me a lot.
As mentioned in the title, i can not see where errors are happening, because the logicMiddleware is probably catching them. 

You can easily reproduce that by adding line

```
console.log("provocate error",action.some.not.existing.value)
```

into your countdown-obs example in the reducer file like following:

```
 //...
  case TIMER_START:
      console.log("provocate error",action.some.not.existing.value)
    return {
      ...state,
      status: 'started'
    };
  //...
```

If you click start in the browser nothing happens and it is very hard to locate the error. 
I tried to find where this might happen in the source code, but unfortunatly i was unable to do so.

Do you have an idea?

Best greets

**Comment by jeffbski** [comment]
@farukg Thanks for writing. Have you tried the latest version? I just made a change in v0.12.2 which console.errors any errors from reducer, renderer, or middleware stack that would have previously be hidden. The example might still be installing an older version, but if you update it `npm i -S redux-logic@latest` then it should be logging the error in the console.

**Comment by farukg** [comment]
Hey, just tried and it works! thank you very much :))

**Comment by jeffbski** [comment]
Awesome! Glad to hear it. Thanks for letting me know.
