### ISSUE TITLE
"latest: true" option is not working...

### ISSUE THREAD

**Issue by josephfischer** [jeffbski/redux-logic#71]
In the following code snippet (using websockets), using the option "latest: true" does not prevent this action from executing multiple times before done() is invoked...

createLogic({
  type: 'TENDER_BUTTON',
  latest: true,
  process({ action, getState }, dispatch, done) {
      websocketClient.request(requests.PAY_NOW)
        .then(() => {
            websocketClient.request(request.TENDER).then(() => {
            browserHistory.push('/tender');
            done();
        });
    }
  }
}); 

In the console, we can see this action is invoked each time the user clicks a button before done is called.  We are using "redux-logic": "0.12.2".  Any idea what we are doing wrong or is this a defect?

**Comment by jeffbski** [comment]
Well it sounds like a misunderstanding of what latest:true does. What it does is that if another request comes in while one is already running (before it has completed) then it ignores the dispatch from the original one and just waits for the response of the latest one. 

So in your example multiple clicks will all be sent, it's only the latest dispatch that would be used if there were multiple overlapping.

Best way to handle this is to simply disable the button after first press until it completes.

Alternatively if you wanted to use something like `throttle: 1000` that would only allow the first button press through blocking any others that occur in the next 1000ms. However this wouldn't be as nice as disabling the button and re-enabling when complete, that would be your best way to do it.
