### ISSUE TITLE
Get rid of rxjs dependency

### ISSUE THREAD

**Issue by binarykitchen** [jeffbski/redux-logic#72]
Seeing that it needs `npm install rxjs --save` puts me away to use redux-logic.

For a couple of reasons. Also makes me wonder why redux-logic really need reactive extensions when React/Redux already has that stuff?

**Comment by jeffbski** [comment]
I would suggest that the features that RxJS provides are quite different than that of React/Redux.

The primary use of RxJS in redux-logic is to orchestrate events over time. So it does the work of being able to provide cancellation, debouncing, throttling, long lived event streams like when working with web sockets.

Once Observables become part of JS then we'll likely be able to switch to the built-in features rather than needing RxJS and that will eliminate the need to install rxjs. https://tc39.github.io/proposal-observable/ (Note that even now we only import select operations from rxjs to help keep bundle size down).

I'm certainly always open to new ideas or how you see that React/Redux already has the features we need. Please enlighten me.

**Comment by binarykitchen** [comment]
I see. Really like the improvements redux-logic brings in, just dislike the RxJS dependency.

Wondering which npm package comes the most close to redux-logic which would work with React/Redux without RxJS right away @jeffbski ?

**Comment by jeffbski** [comment]
It really depends on what features you would like to use. you can always do your own custom middleware or if you like generators you can try sagas. I tried to outline the various approaches in my article http://codewinds.com/blog/2016-08-16-business-logic-redux.html (also available on medium). 

Is there a particular reason that you don't want to include RxJS? (just trying to understand why) With RxJS version 5, it allows custom builds which we take advantage of (importing only select parts) so the file size is minimal (probably less than many graphics).

**Comment by binarykitchen** [comment]
well, we already have lots of packages in our project, also for promises, and there is no need for us to include rxjs at all. would only complicate things for many reasons.

es6 + es7 already come with promises and useful stuff for observables, so why not shim those and leave it to the bundling tool of your choice to cope with these?

**Comment by zdila** [comment]
In our case `RxJS` takes 4.4% (70k actual / 160.7K raw) from our not-the-smallest webapp. Reported by Webpack Visualizer.

**Comment by tylerlong** [comment]
I used to dislike RxJS dependency a lot but now I am OK with it. RxJS is very flexible and powerful. It is way more powerful than just Promise. For example, you can cancel an action, you can debounce actions...etc. 

Almost every Node.js project has a ton of npm dependencies, either directly or indirectly. If you don't think so please just open the `node_modules/` folder and count how many folders are there. There is not a lot that we can do to change this fact. We should just accept the fact and enjoy it :)

@jeffbski I think lots of people will ignore this issue if you change RxJS from peerDependency to dependency. Then it is required indirectly which doesn't require explicitly installation. 

Just my opinion though. "Dependency hell" is so common in Node.js world and it's not just redux-logic's issue.

**Comment by zdila** [comment]
> Almost every Node.js project has a ton of npm dependencies...

It is OK for nodejs projects, but for webapps devs would like to make their bundle as small as possible.

Some stats from webpack with our webapp - packages ordered by size
- react-dom 14.9%
- code.js 7.1%
- rxjs 4.6%
...
- react 2%
...
- redux logic 1%
...

**Comment by binarykitchen** [comment]
well, it's simple why we are hesitating to use this package:
first it goes against the fundamental modular "lego" approach for building apps based on libraries.
secondly, because we already have other libraries coming with very similar functions reactive extensions have. why should we add "duplicate" code then? it is not about size, we just don't want to be forced to install it because it's a peer dependency, making our package.json longer.

either move this inside dependencies to "hide" this. or to create a second npm package without the rxjs dependency and shim calls/functions to rxjs

**Comment by amankkg** [comment]
Guys you can take a look at [most.js](https://github.com/cujojs/most) as rxjs alternative. But I'm not sure if it suits all redux-logic use cases 🤔.
This issue just reminded me of [redux-most](https://github.com/joshburgess/redux-most#background).
IMO rxjs dependency is still preferable in sense of helping to popularize this library

**Comment by jeffbski** [comment]
@tylerlong Thanks for that idea. I guess we could change it to a direct dependency to eliminate the separate install. The reason I originally had it as peer dependency is so people would have more flexibility in choosing whatever version they wanted in case they needed a specific version for certain tools and to help make sure there was only one copy of rxjs in the tree. 

I guess that even if it was dep they could still install a specific version and as long as it was compatible it should not install additional ones. 

It looks like redux-observable uses a peerDependency and a devDependency which wouldn't really help anything as far as this problem goes.

I guess I'll plan on switching to a regular dependency. Will ponder just a bit more and then will make the change.

**Comment by jeffbski** [comment]
@amankkg thanks for mentioning most.js It looks pretty nice. I'll learn more about it.

**Comment by jeffbski** [comment]
I have pushed a new version v0.12.3 which makes rxjs a dependency

 https://github.com/jeffbski/redux-logic/pull/77

So I'll go ahead and close this for now.
