### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by nicholaswyoung** [jeffbski/redux-logic#8]
I'm writing an app in TypeScript, and it would be nice to have definitions to aid in syntax completion, etc. 

Provided that you're open to this, I'll finish what I've written so far and submit a pull request.

**Comment by jeffbski** [comment]
Absolutely. I knew that we needed it, but I'm not versed enough in TS to do it yet. So any help is appreciated.

**Comment by rob3c** [comment]
@nicholaswyoung Did you ever end up distributing your type definitions somewhere?

**Comment by jeffbski** [comment]
added in 0.15.3
