### ISSUE TITLE
Logic that executes on state change

### ISSUE THREAD

**Issue by zdila** [jeffbski/redux-logic#9]
Hello. Is there a way to configure Logic to fire when some deep state changes?

It would be a different approach where instead of running business code on `FETCH_POLLS` there would be only dispatched action like `FETCH_POLLS_START` which would set state `polls.fetching` to `true`. A Logic would run when it would detect transition of `polls.fetching` from `false` to `true`. This would bring interception based not on action type but on state change, which is even more general.

There are projects like redux-watch which solves only this part. Could it be conbined with redux-logic?

What do you think?

**Comment by jeffbski** [comment]
I hadn't considered this use case but I don't see why it wouldn't work.

The easiest thing to do would be to create logic which listens to action type '*' (or a regex or array of action types that could possibly change the deep state you are interested in). 

It would have compare the deep state to the previous state and if different trigger what ever you would want to happen and store the new state for the next comparison.

Here is example code:

```js
let lastPollsFetching = false; // always keeps the last state to compare against
const pollsFetchingWatchLogic = createLogic({
  type: '*',  // or a regex or array of action types that could change pollls.fetching
  process({ getState, action }, dispatch) {
    const pollsFetching = getState().polls.fetching;
    if (lastPollsFetching != pollsFetching) { // state has changed 
      lastPollsFetching = pollsFetching; // update local copy so doesn't trigger twice
      if (!pollsFetching) { return dispatch(); } // only fetching if truthy
      axios.get('/foo')
        .then(resp => resp.data.polls)
        .then(polls => {
          dispatch({ type: FETCH_POLLS_SUCCESS, payload: polls });
        })
        .catch(err => {
           dispatch({ type: FETCH_POLLS_ERROR, payload: err, error: true });
        });
    } else { // pollsFetching not updated, dispatch empty to end processing, nothing else to do
      dispatch();
    }
  }
);
```

So this basically would fire on any action type (so anything that could change state), then we quickly determine whether the state we care about pollsFetching has changed and either do something or not. If it is easy to limit down what actions might possibly change the state then you could use a regex or array of strings/regex to further restrict this logic to run only after those actions further improving performance. 

I'll take a look at redux-watch and also give it some more thought, but the above would be a solution given the current api.

**Comment by zdila** [comment]
Yes, it is doable as you describe but then the main feature of redux-logic is not used.

I allways wonder why almost all similar libraries execute business logic on action and only few on state change. I think that there are many usecases for executing business logic on state change.

**Comment by jeffbski** [comment]
I think we can close this issue for now, we can revisit later as necessary.

**Comment by zdila** [comment]
My (quick) proposal:

```
createWatcher({
  debounce: ...,
  throttle: ...,
  latest: ...,
  warnTimeout: ...,
    
  // called before and after reducer to get old and new value for comparation
  getWatchedValue({ action, getState }) {
    return getState().someProperty;
  },

  // optional function to detect the change
  detectChange(oldValue, newValue) {
    return oldValue !== newValue; // default implementation
  },

  // called when value has changed
  onValueChange(/* same signature as process(...) */) {
    //
  },

  /* state-change based cancellation - this could be also in createLogic(...) */

  // called before and after reducer
  cancelGetWatchedValue({ action, getState }) {
    return getState().someProperty;
  },

  // optional
  cancelDetectChange(oldValue, newValue) {
    return oldValue === newValue;
  },
});
```

**Comment by jeffbski** [comment]
Thanks for the suggestion @zdila. I'm thinking about all of this.
