### ISSUE TITLE
Possibility to filter on action parameters? 

### ISSUE THREAD

**Issue by henninghall** [jeffbski/redux-logic#97]
Is there any possibility to filter actions on more properties than type? Something that achieves this in a cleaner way:
```
const action = {
    type: 'REQUEST_SUCCESS',
    requestType: 'GET_USERS'
} 

createLogic({

    type: 'REQUEST_SUCCESS'
    
    process({ action }) {
        if (action.requestType === 'GET_USERS') {
        ...
        }
        done()
    }
})

```

**Comment by jeffbski** [comment]
Currently that is the way to do it, but in a future version I could provide a `filter` property as an alternative to type that would allow you to specify the filter predicate fn so you could do whatever filtering you want. 

That would allow you to split up your logic items by requestType more easily.

I'll mark this as a feature request.

**Comment by henninghall** [comment]
Thanks for the reply, that would be great solution!

I am not sure if this is a bad option but wouldn't it also be possible to use the current validate property and change it to accept a boolean return value instead of allow/reject? Like this: 

Current implementation: 
```
 validate({ getState, action }, allow, reject) {
        (action.requestType === 'GET_USERS') ? allow(action) : reject(action);
    }, 
```

Validate that accepts boolean return values: 

```
 validate = ({ getState, action}, allow, reject) => (action.requestType === 'GET_USERS')
```
