### ISSUE TITLE
Dispatch does not work in axios catch callback

### ISSUE THREAD

**Issue by micahblu** [jeffbski/redux-logic#98]
I'm using axios for an ajax call with a timeout in place. When I mock the timeout which is handled by the catch() callback, dispatch does not work? 

```js
import { createLogic } from 'redux-logic'
import axios from 'axios'
import { doSomething } from 'shared/actions'

export const doSomethingLogic = createLogic({
  type: 'ACTION',
  process({ getState, action }, dispatch, done) {
    let params = {
      foo: 'bar'
    }
    axios.bind(this)
    axios.get( '/do-something', {
      params,
      timeout: 5000
    })
    .then(response => response.data)
    .then(response => {
      dispatch(doSomething()) // works!
      done()
    })
    .catch(err => {
      console.log('err', err)
      console.log('dispatch', dispatch) // shows the dispatch function?
      dispatch(doSomething()) // does not work :/
      done()
    })
  }
})
```
Thanks for any help

**Comment by jeffbski** [comment]
That's very strange. So I assume you are seeing the proper err in the console.log and not something else. 

I don't see anything wrong from what you have indicated here.

When you mock the timeout, is your axios.get still returning a promise? I remember a few times when I was mocking that I forgot to return a promise and that's why it wasn't working.

If none of that helps, could you provide more of your test and mock, maybe that will help me see the problem.

**Comment by micahblu** [comment]
@jeffbski I do see the proper error. I also confirmed that axios is returning a promise. So I've removed axios completely to try and isolate the issue and lo and behold with even setTimeout(), the dispatch within timeout does not work?

So now I have: 
```js
import { createLogic } from 'redux-logic'
import axios from 'axios'
import { doSomething } from 'shared/actions'

export const doSomethingLogic = createLogic({
  type: 'ACTION',
  process({ getState, action }, dispatch, done) {
    setTimeout(() => {
      console.log('dispatch', dispatch) // shows the dispatch function?
      dispatch(doSomething()) // does not work :/
      done()
    })
  }
})
```

**Comment by jeffbski** [comment]
Is there any chance that doSomething() is throwing an error?

Or another thing could be that when it actually tries to dispatch that it is causing an error somewhere maybe in a reducer?

**Comment by micahblu** [comment]
@jeffbski This was an unrelated issue found on my end. I really appreciate your help and patience. Sorry for the false alarm!

**Comment by jeffbski** [comment]
excellent! I'm glad you found it.

**Comment by by12380** [comment]
Not sure if the problem was identical, but when I placed `return` before `axios` in my async action the dispatch in `.catch()` callback worked. It was expecting a `Promise` for return. Not sure why it did not matter for dispatches in `.then()`
